name: ANW Volta App Build APK

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Install Cordova
        run: |
          npm install -g cordova
          npm install -g cordova-res
      - name: Install dependencies
        run: |
          npm install

      - name: Upload Google Services JSON
        uses: actions/upload-artifact@v2
        with:
          name: google-services
          path: ./android/app/google-services.json

      - name: Build Android APK
        run: |
          ls
          pwd
          ionic cordova platform add android
          cordova build android

      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: ./platforms/android/app/build/outputs/apk/debug/app-debug.apk
