name: ANW Volta App Build APK
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Install Cordova
        run: |
          npm install -g cordova
          npm install -g cordova-res
      - name: Install dependencies
        run: |
          npm install

      - name: Upload Google Services JSON
        uses: actions/upload-artifact@v4
        with:
          name: google-services
          path: ./google-services.json

      - name: Download Google Services JSON
        uses: actions/download-artifact@v4
        with:
          name: google-services
          path: ./platforms/android/app

      - name: Add Remove Android Platform
        run: |
          ls
          pwd
          ionic build
          ionic cordova platform rm android
          ionic cordova platform add android

      - name: Platform Files
        run: ls -R $GITHUB_WORKSPACE/platforms/android/platform_www

      - name: www Files
        run: ls -R $GITHUB_WORKSPACE/www

      - name: Copy cordova.js
        run: cp $GITHUB_WORKSPACE/platforms/android/platform_www/cordova.js $GITHUB_WORKSPACE/www/

      - name: Add cordova.js reference
        run: sed -i 's#</html>#<script src="cordova.js"></script></html>#' $GITHUB_WORKSPACE/www/index.html

      - name: Build APK
        run: cordova build android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: voltaapp
          path: ./platforms/android/app/build/outputs/apk/debug/app-debug.apk

      - name: Save Run ID
        id: save_run_id
        run: echo "::set-output name=run_id::${{ github.run_id }}"

      - name: Trigger BrowserStack Mobile App Tests
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAS_TOKEN }}
          repository: appnetwise/anw-app-browserstack
          event-type: run-browserstack-tests
